version: "3.8"

services:
  go-app1:
    build:
      context: .
      args:
        - PORT=8080
    container_name: go-app1
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - wsgo-network

  go-app2:
    build:
      context: .
      args:
        - PORT=8081
    container_name: go-app2
    environment:
      - PORT=8081
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - wsgo-network

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - wsgo-network

  nginx:
    image: nginx:alpine
    restart: always
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - go-app1
      - go-app2
    networks:
      - wsgo-network

networks:
  wsgo-network:
    driver: bridge
